[tool.black]
line-length = 90
target-version = ['py311']
exclude = '''
/(
\.direnv
|\.eggs
|\.git
|\.venv
|\\env
|\\.ipynb_checkpoints
|\\.mypy_cache
|\\.pytest_cache
|\\.ruff_cache
|\\.tox
|\\.svn
|\\.venv
|\\.vscode|pypackages|_build|buck-out|build|dist|venv
)/
'''

[tool.isort]
profile = "black"
line_length = 90
skip = [
    "venv",
    ".venv",
    "env",
    ".git",
    "allure-results",
    "allure-report",
    ".pytest_cache",
]

[tool.pytest.ini_options]
addopts = [
    "--alluredir=allure-results",
    "--clean-alluredir",
    "-l",
    "-v",
    # "--durations=10"

]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"').",
    "fast: marks tests as fast (deselect with '-m \"not fast\"')."
]
